# Generated by Django 4.1 on 2022-09-07 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('description', models.TextField(verbose_name='Текст')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Заголовок')),
                ('category_new', models.ManyToManyField(to='newsproj.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='NewCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsproj.category')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsproj.new')),
            ],
        ),
    ]
